### ISSUE TITLE
Permissions for channel type do not work as expected

### ISSUE THREAD

**Issue by SviatKuzma** [GetStream/stream-chat-php#36] opened 2020-12-28 14:12 UTC
I have a list of permissions where the user can only read messages from this type of channel

```
[
	{
		"action": "Allow",
		"name": "admin can do almost anything",
		"resources": [
			"CreateChannel",
			"ReadChannel",
			"UpdateChannelMembers",
			"UpdateChannel",
			"DeleteChannel",
			"CreateMessage",
			"UpdateMessage",
			"DeleteMessage",
			"BanUser",
			"UploadAttachment",
			"DeleteAttachment",
			"UseCommands",
			"AddLinks",
			"EditUser",
			"RunMessageAction",
			"CreateReaction",
			"DeleteReaction",
			"SendCustomEvent",
			"RemoveOwnChannelMembership"
		],
		"roles": [
			"admin"
		],
		"owner": false,
		"priority": 999
	},
	{
		"action": "Deny",
		"name": "No guests or anonymous access",
		"resources": [
			"*"
		],
		"roles": [
			"anonymous",
			"guest"
		],
		"owner": false,
		"priority": 90
	},
	{
		"action": "Allow",
		"name": "Owner permissions",
		"resources": [
			"ReadChannel",
			"UpdateChannelMembers",
			"UpdateChannel",
			"DeleteChannel",
			"UpdateMessage",
			"DeleteMessage",
			"EditUser",
			"DeleteAttachment",
			"DeleteReaction"
		],
		"roles": [],
		"owner": true,
		"priority": 80
	},
	{
		"action": "Allow",
		"name": "Channel member permissions",
		"resources": [
			"ReadChannel",
			"RunMessageAction"
		],
		"roles": [
			"channel_member",
			"channel_moderator"
		],
		"owner": false,
		"priority": 70
	},
	{
		"action": "Allow",
		"name": "Users can read channels",
		"resources": [
			"ReadChannel"
		],
		"roles": [
			"user"
		],
		"owner": false,
		"priority": 60
	},
	{
		"action": "Allow",
		"name": "Moderator only features",
		"resources": [
			"UpdateChannelMembers",
			"UpdateChannel",
			"UpdateMessage",
			"DeleteMessage",
			"BanUser",
			"DeleteAttachment",
			"UploadAttachment"
		],
		"roles": [
			"channel_moderator"
		],
		"owner": false,
		"priority": 50
	},
	{
		"action": "Deny",
		"name": "deny all policy",
		"resources": [
			"*"
		],
		"roles": [
			"*"
		],
		"owner": false,
		"priority": 1
	}
]
```

but `user` still can send a message to this channel

```
{
    "message": {
        "id": "4617-ba99a8a0-5926-4ea9-9710-ee7dc7def8e1",
        "text": "sdsd",
        "html": "<p>sdsd</p>\n",
        "type": "regular",
        "user": {
            "id": "4617",
            "role": "user",
            "created_at": "2020-12-23T13:29:49.643007Z",
            "updated_at": "2020-12-28T14:00:04.951443Z",
            "last_active": "2020-12-28T14:00:04.951443Z",
            "banned": false,
            "online": true,
            "image": "",
            "name": "Borro "
        },
        "attachments": [],
        "latest_reactions": [],
        "own_reactions": [],
        "reaction_counts": null,
        "reaction_scores": {},
        "reply_count": 0,
        "created_at": "2020-12-28T14:11:31.173896Z",
        "updated_at": "2020-12-28T14:11:31.173896Z",
        "shadowed": false,
        "mentioned_users": [],
        "silent": false
    },
    "duration": "14.06ms"
}
```

gz#8269

**Comment by shodgetts** [comment] 2020-12-28 14:39
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8269'>Zendesk ticket #8269</a>:<br><br>Hi,

Thanks for getting in touch. We will look into this and get back to you as soon as possible.

Best,
Ryan

**Comment by shodgetts** [comment] 2020-12-28 19:06
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8269'>Zendesk ticket #8269</a>:<br><br>Hey,

Could you please provide the appID and and channel type associated with these permissions when you have a moment?

Best,
Ryan

**Comment by SviatKuzma** [comment] 2020-12-29 08:06
Sure,
first
AppID - 102881
Channel type - notice_board

and second

AppID - 103027
Channel type - notice_board

**Comment by shodgetts** [comment] 2020-12-29 14:16
Agent comment from Stephen Hodgetts in <a href='https://getstream.zendesk.com/agent/tickets/8269'>Zendesk ticket #8269</a>:<br><br>Hello, you have disabled permission checks for this app, so none of the changes (or even any of the permissions in general) will make a difference to this app. You can switch this back in the dashboard and read more about it here
https://getstream.io/chat/docs/application_settings/?language=js#permission-settings
Stephen

**Comment by AnatolyRugalev** [comment] 2021-10-04 08:06
Closing as the issue is not related to PHP SDK

**Closed by AnatolyRugalev** 2021-10-04 08:06 UTC
